version: '3'

services:
  server:
    image: 'erivelto/server-form-user'
    build:
      context: server
    container_name: server
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/form_data
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - 3000:3000

  client:
    image: 'erivelto/client-form-user'
    build:
      context: client-form
    ports:
      - "4200:80"
    depends_on:
      - "server"

  db:
    image: 'postgres'
    container_name: db
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
      - POSTGRES_DB=form_data
